// Package cli — inspect.go
//
// `afcli inspect <target>` walks the target's `--help` output recursively
// (depth ≤ 3, total visits ≤ 50) and emits an `afcli.yaml` descriptor
// scaffold populated with discovered safe verbs and `# REVIEW:` markers
// for verbs that look destructive. The emitted body is guaranteed to
// round-trip through `descriptor.Load` so downstream `afcli audit
// --descriptor` runs see a non-trivial verdict.
//
// Authorization boundary (S02-RESEARCH): inspect runs the user-supplied
// target via `--help` only. The user typing the target on argv IS the
// authorization — there is NO descriptor available (we are generating
// one), so `authorizeProbe` is intentionally NOT called from this path.

package cli

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/agentfirstcli/afcli/internal/audit"
	"github.com/agentfirstcli/afcli/internal/exit"
	"github.com/agentfirstcli/afcli/internal/report"
	"github.com/spf13/cobra"
)

// inspectOutPath mirrors --out on inspectCmd. Default empty means
// stdout. MEM045: must NOT be named --output — that is the persistent
// root flag (json/text/markdown) and would silently shadow a per-command
// --output flag.
var inspectOutPath string

// inspectProbeTimeout mirrors --probe-timeout on inspectCmd. The 5s
// default matches audit's per-probe ceiling so a slow target cannot
// wedge the recursive walk; the worst-case ceiling is
// inspectMaxVisits × inspectProbeTimeout.
var inspectProbeTimeout time.Duration

// inspectMaxDepth bounds recursion depth and inspectMaxVisits bounds
// total subcommand visits. Both are required: depth alone does not
// stop fanout, visit count alone does not stop pathological aliases
// from re-entering the same node.
const (
	inspectMaxDepth  = 3
	inspectMaxVisits = 50
)

// inspectTemplate is the literal YAML body emitted by `afcli inspect`.
// We do NOT use yaml.Marshal because (a) Descriptor's omitempty tags
// would suppress the explicit-empty scaffold keys (env, skip_principles,
// relax_principles) and (b) we need stable indentation plus inline
// `# REVIEW:` comments which Marshal cannot produce. Every spliced
// token is run through strconv.Quote so quotes/backslashes from
// real-world `--help` output cannot break out of the YAML string.
const inspectTemplate = `# afcli.yaml — generated by ` + "`afcli inspect <target>`" + `.
#
# Destructive-looking verbs discovered in the target's --help output are
# surfaced below as commented ` + "`# REVIEW:`" + ` candidates. afcli will NEVER
# run them unless you explicitly move an entry into commands.destructive[]
# after reviewing the underlying behavior.
<REVIEW_BLOCK>
format_version: "1"
target: "<TARGET>"
commands:
  safe:<SAFE_LIST>
  destructive: []
<DESTRUCTIVE_BLOCK>
env: {}
skip_principles: []
relax_principles: {}
`

// inspectAggregate accumulates discovered safe and destructive verbs
// across every level of the recursive walk. Sets dedupe across the
// entire walk; the final YAML emits sorted slices for byte-determinism.
type inspectAggregate struct {
	safe        map[string]struct{}
	destructive map[string]struct{}
}

func newInspectAggregate() *inspectAggregate {
	return &inspectAggregate{
		safe:        map[string]struct{}{},
		destructive: map[string]struct{}{},
	}
}

// walkHelp recursively probes target via `<prefix...> --help`, parses
// captured stdout for safe / destructive / subcommand candidates, and
// recurses into each discovered subcommand. depth tracks the current
// recursion level (0 for the top-level call). visited dedupes prefixes
// across the whole walk and enforces inspectMaxVisits.
func walkHelp(ctx context.Context, target string, prefix []string, depth int, visited map[string]bool, agg *inspectAggregate) {
	if ctx.Err() != nil {
		return
	}
	key := strings.Join(prefix, " ")
	if visited[key] {
		return
	}
	if len(visited) >= inspectMaxVisits {
		return
	}
	visited[key] = true

	args := append(append([]string(nil), prefix...), "--help")
	c := audit.RunProbe(ctx, target, args, inspectProbeTimeout, nil)
	// Parse whatever stdout the probe produced — even a non-zero exit
	// or timeout may have printed a usage block before failing. ParseHelp
	// degrades to empty results on unrecognised output (flag.Parse
	// fixtures fall through this path).
	safeVerbsFound, subs, destrCandidates := ParseHelp(c.Stdout)
	for _, v := range safeVerbsFound {
		agg.safe[v] = struct{}{}
	}
	for _, v := range destrCandidates {
		agg.destructive[v] = struct{}{}
	}

	if depth >= inspectMaxDepth {
		return
	}
	for _, sub := range subs {
		// "help" is auto-injected by Cobra; recursing into nested help
		// chains burns visit budget without producing new safe verbs.
		if sub == "help" {
			continue
		}
		if len(visited) >= inspectMaxVisits {
			return
		}
		next := append(append([]string(nil), prefix...), sub)
		walkHelp(ctx, target, next, depth+1, visited, agg)
	}
}

// renderInspectYAML splices target/safe/destructive into inspectTemplate.
// Output is byte-deterministic for a given (target, agg) input: keys
// sorted, every spliced string strconv.Quote'd.
func renderInspectYAML(target string, agg *inspectAggregate) []byte {
	safeList := sortedKeys(agg.safe)
	destrList := sortedKeys(agg.destructive)

	body := inspectTemplate

	var review strings.Builder
	if len(destrList) > 0 {
		review.WriteString("#\n")
		for _, v := range destrList {
			review.WriteString("# REVIEW: ")
			review.WriteString(strconv.Quote(v))
			review.WriteString(" looked destructive (heuristic match)\n")
		}
	}
	body = strings.Replace(body, "<REVIEW_BLOCK>", strings.TrimRight(review.String(), "\n"), 1)

	body = strings.Replace(body, `"<TARGET>"`, strconv.Quote(target), 1)

	var safeBlock string
	if len(safeList) == 0 {
		safeBlock = " []"
	} else {
		var b strings.Builder
		b.WriteString("\n")
		for i, v := range safeList {
			b.WriteString("    - ")
			b.WriteString(strconv.Quote(v))
			if i < len(safeList)-1 {
				b.WriteString("\n")
			}
		}
		safeBlock = b.String()
	}
	body = strings.Replace(body, "<SAFE_LIST>", safeBlock, 1)

	var destrBlock strings.Builder
	for i, v := range destrList {
		destrBlock.WriteString("  # REVIEW: ")
		destrBlock.WriteString(strconv.Quote(v))
		if i < len(destrList)-1 {
			destrBlock.WriteString("\n")
		}
	}
	body = strings.Replace(body, "<DESTRUCTIVE_BLOCK>", destrBlock.String(), 1)

	return []byte(body)
}

func sortedKeys(m map[string]struct{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

var inspectCmd = &cobra.Command{
	Use:   "inspect <target>",
	Short: "Walk a target's --help recursively and emit a populated afcli.yaml scaffold",
	Long: "Probe the named target via --help (recursing into discovered subcommands\n" +
		"up to depth 3 / 50 total visits) and emit an afcli.yaml descriptor body\n" +
		"to stdout (or --out PATH). Discovered safe verbs land in commands.safe[];\n" +
		"verbs that look destructive (delete, apply, push, ...) are surfaced ONLY\n" +
		"as commented `# REVIEW:` markers — afcli never auto-promotes them into\n" +
		"the active commands.destructive[] list.",
	// --help-schema short-circuits in PersistentPreRunE, but Cobra runs
	// ValidateArgs before PersistentPreRunE, so we have to skip the
	// arg-count check ourselves when the user is asking for the schema
	// or the version (mirrors init.go and audit.go).
	Args: func(cmd *cobra.Command, args []string) error {
		if helpSchema || versionFlag {
			return nil
		}
		return cobra.ExactArgs(1)(cmd, args)
	},
	SilenceUsage:  true,
	SilenceErrors: true,
	RunE: func(cmd *cobra.Command, args []string) error {
		target := args[0]

		resolved, err := exec.LookPath(target)
		if err != nil {
			return classifyResolveError(target, err)
		}

		ctx, cleanup := InstallSignalHandler(cmd.Context())
		defer cleanup()

		visited := map[string]bool{}
		agg := newInspectAggregate()
		walkHelp(ctx, resolved, nil, 0, visited, agg)

		body := renderInspectYAML(target, agg)

		if inspectOutPath == "" {
			if _, werr := cmd.OutOrStdout().Write(body); werr != nil {
				return newAuditError(
					report.CodeInternal,
					fmt.Sprintf("could not write descriptor to stdout: %v", werr),
					"check that stdout is writable",
					target,
					map[string]any{"target": target, "os": werr.Error()},
					exit.Internal,
				)
			}
			return nil
		}

		if werr := os.WriteFile(inspectOutPath, body, 0o644); werr != nil {
			return newAuditError(
				report.CodeInternal,
				fmt.Sprintf("could not write descriptor: %v", werr),
				"check that the parent directory exists and is writable",
				inspectOutPath,
				map[string]any{"path": inspectOutPath, "os": werr.Error()},
				exit.Internal,
			)
		}
		return nil
	},
}

func init() {
	inspectCmd.Flags().StringVar(&inspectOutPath, "out", "", "path to write the descriptor (default: stdout)")
	inspectCmd.Flags().DurationVar(&inspectProbeTimeout, "probe-timeout", 5*time.Second, "per-probe timeout for each --help invocation (default 5s)")
}
